version: '3'
services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-downloader
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
    - ./state:/opt/dldr/state
    - ./attachments:/opt/dldr/attachments
